language: python
sudo: false
dist: trusty

cache: pip

services:
 - docker

env:
  global:
    - TOOLS_DIR=${HOME}/bin
    - PATH="${TOOLS_DIR}:${PATH}"
    - KUBECONFIG="${HOME}/.kube/kubernaut"
    - SCOUT_DISABLE=1
    - KUBECTL_VERSION=1.7.5    
    - FORGE_VERSION=0.3
    - KUBE_DNS_NAME=bdd.datawire.io

before_install:
  - openssl aes-256-cbc -K $encrypted_a5fc079e249b_key -iv $encrypted_a5fc079e249b_iv -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar
  - chmod 644 forge.yaml kubernaut
  - mkdir -p ${HOME}/.kube
  - mkdir -p ${TOOLS_DIR}
  - mv kubernaut ${HOME}/.kube/kubernaut

install:
  - curl https://s3.amazonaws.com/datawire-static-files/forge/$FORGE_VERSION/forge -o ${TOOLS_DIR}/forge
  - chmod a+x ${TOOLS_DIR}/forge
  - curl -L --output ${TOOLS_DIR}/kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
  - chmod a+x ${TOOLS_DIR}/kubectl
  - kubectl version
  - kubectl cluster-info
  - forge --version

script:
  - forge deploy --namespace=staging
  - sleep 10s
  - export HELLO_PORT="$(kubectl get service -n staging hello -o jsonpath='{.spec.ports[0].nodePort}')"
  - echo $HELLO_PORT
  - curl -4v "http://${KUBE_DNS_NAME}:${HELLO_PORT}/"
  - curl -4v "http://${KUBE_DNS_NAME}:${HELLO_PORT}/quote"
  - forge deploy --namespace=prod
