language: python
sudo: false
dist: trusty

cache: pip

services:
 - docker

env:
  global:
    - KUBECONFIG="${HOME}/.kube/kubernaut"
    - SCOUT_DISABLE=1
    - KUBECTL_VERSION=1.7.5    
    - FORGE_VERSION=0.3

before_install:
  - openssl aes-256-cbc -K $encrypted_a5fc079e249b_key -iv $encrypted_a5fc079e249b_iv -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf /secrets.tar
  - chmod 644 forge.yaml kubernaut
  - mkdir -p ${HOME}/.kube
  - mv kubernaut ${HOME}/.kube/kubernaut

install:
  - curl https://s3.amazonaws.com/datawire-static-files/forge/$FORGE_VERSION/forge -o /tmp/forge
  - chmod a+x /tmp/forge
  - mv /tmp/forge /usr/local/bin
  - curl -L --output /tmp/kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
  - mv /tmp/kubectl /usr/local/bin
  - chmod +x /usr/local/bin/kubectl
  - kubectl --version
  - forge --version
