---
apiVersion: v1
kind: Service
metadata:
  name: {{ service.name }}
spec:
  type: NodePort  
  selector:
    app: {{ service.name }}
  ports:
  - port: 80
    targetPort: http-api

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ service.name }}
    spec:
      containers:
      - name: {{ service.name }}
        image: {{ build.images["Dockerfile"] }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: http-api
          containerPort: 5000
