---
apiVersion: v1
kind: Service
metadata:
  name: quote
spec:
  type: ClusterIP
  selector:
    app: quote
  ports:
  - port: 80
    targetPort: http-api

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quote
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: qotm
        image: {{ build.images["Dockerfile"] }}
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 5000
